### ISSUE TITLE
Graphics errors

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/dwarf-term-rs#1]
The topic where I collect info on graphical errors with dwarf term.

**Comment by ThatsNoMoon** [comment]
Blank white screen

OS:
Win 10 x64 Build 17134

PC:
CPU - i5 2500
RAM - 8GB
GPU - RX 560 driver v. 18.5.2

**Comment by blueridanus** [comment]
[Triangles all over the window, with one question mark near the bottom left, all green](https://i.imgur.com/2GsfiG9.png)

OS:
Arch Linux x64, Mesa 18.1.1
Max core profile version: 3.3


PC:
CPU - Intel(R) Core(TM) i3-2330M CPU @ 2.20GHz
RAM - 4GB
GPU - Intel embedded graphics

**Comment by HooniusDev** [comment]
Triangles all over the window, with one question mark near the bottom left, all green

OS Info:
Win10 x64 v1803, build 17134.112
Hardware:
CPU - i5-3317U
RAM - 16GB
GPU - Inter(R) HD Graphics 4000

**Comment by Lokathor** [comment]
So,

* The blank white screen is an assert failure in the shader, it blanks the screen since the gpu can't panic or print to std err or anything.
* The wrong tiles displayed is some sort of rounding error. Some of the tiles are displaying the data one cell off from the actual id.

The blank screen should be more easily fixable, I hope. The wrong tiles seems to so far only happen with integrated graphics, and that'd maybe be a clue, if i knew more graphics.

**Comment by Lokathor** [comment]
Fixed the blanking in the newest patch. the wrong tile stuff is a mystery at the moment.

**Comment by Lokathor** [comment]
Oh, it was an alignment bug. I never updated this ticket. Oh well.
